parameters:
    dbal.field_names:
        id: 'id'
    dbal.transaction_isolation_level: !php/const Doctrine\DBAL\TransactionIsolationLevel::REPEATABLE_READ
    dbal.use_auto_mapper: false
    dbal.default_dto_group: null
    dbal.chunk_size: 1000
    dbal.oder_direction: 'ASC'

services:

    # Десериалиторы
    ITech\Bundle\DbalBundle\Utils\SymfonyDtoDeserializer:
        arguments:
            $serializer: '@serializer'
            $defaultGroup: '%dbal.default_dto_group%'

    ITech\Bundle\DbalBundle\Utils\AutoMapperDtoDeserializer:
        arguments:
            $autoMapper: '@?AutoMapper\AutoMapperInterface'

    ITech\Bundle\DbalBundle\Utils\DtoDeserializerFactory:
        arguments:
            $symfonyDeserializer: '@ITech\Bundle\DbalBundle\Utils\SymfonyDtoDeserializer'
            $autoMapperDeserializer: '@?ITech\Bundle\DbalBundle\Utils\AutoMapperDtoDeserializer'
            $useAutoMapper: '%dbal.use_auto_mapper%'

    ITech\Bundle\DbalBundle\Utils\DtoDeserializer:
        factory: [ '@ITech\Bundle\DbalBundle\Utils\DtoDeserializerFactory', 'create' ]

    ITech\Bundle\DbalBundle\Utils\DtoDeserializerInterface:
         alias: ITech\Bundle\DbalBundle\Utils\DtoDeserializer

    # FieldSelector
    ITech\Bundle\DbalBundle\Service\Dto\DtoFieldExtractor:
        arguments: []

    ITech\Bundle\DbalBundle\Service\Dto\DtoFieldExtractorInterface:
        alias: ITech\Bundle\DbalBundle\Service\Dto\DtoFieldExtractor

    # Манагеры
    ITech\Bundle\DbalBundle\Config\DbalBundleConfig:
        arguments:
            $useAutoMapper: '%dbal.use_auto_mapper%'
            $defaultDtoGroup: '%dbal.default_dto_group%'
            $chunkSize: '%dbal.chunk_size%'
            $fieldNames: '%dbal.field_names%'
            $orderDirection: '%dbal.oder_direction%'

    ITech\Bundle\DbalBundle\Manager\DbalManagerFactory:
        arguments:
            $dtoDeserializer: '@ITech\Bundle\DbalBundle\Utils\DtoDeserializerInterface'
            $dtoFieldExtractor: '@ITech\Bundle\DbalBundle\Service\Dto\DtoFieldExtractorInterface'
            $config: '@ITech\Bundle\DbalBundle\Config\DbalBundleConfig'

    ITech\Bundle\DbalBundle\Manager\DbalManager:
        factory: [ '@ITech\Bundle\DbalBundle\Manager\DbalManagerFactory', 'createByConnection' ]
        arguments:
            - '@Doctrine\DBAL\Connection'

    ITech\Bundle\DbalBundle\Service\Transaction\TransactionService:
        arguments:
            - '@Doctrine\DBAL\Connection'
            - '%dbal.transaction_isolation_level%'

    ITech\Bundle\DbalBundle\Service\Transaction\TransactionServiceInterface:
        alias: ITech\Bundle\DbalBundle\Service\TransactionService



