parameters:
    dbal.transaction_isolation_level: !php/const Doctrine\DBAL\TransactionIsolationLevel::REPEATABLE_READ
    dbal.use_auto_mapper: false
    dbal.default_dto_group:

services:

    # Десериалиторы
    ITech\Bundle\DbalBundle\Utils\SymfonyDtoDeserializer:
        arguments:
            $serializer: '@serializer'
            $defaultGroup: '%dbal.default_dto_group%'

    ITech\Bundle\DbalBundle\Utils\AutoMapperDtoDeserializer:
        arguments:
            $autoMapper: '@?AutoMapper\AutoMapperInterface'

    ITech\Bundle\DbalBundle\Utils\DtoDeserializerFactory:
        arguments:
            $symfonyDeserializer: '@ITech\Bundle\DbalBundle\Utils\SymfonyDtoDeserializer'
            $autoMapperDeserializer: '@?ITech\Bundle\DbalBundle\Utils\AutoMapperDtoDeserializer'
            $useAutoMapper: '%dbal.use_auto_mapper%'

    ITech\Bundle\DbalBundle\Utils\DtoDeserializer:
        factory: [ '@ITech\Bundle\DbalBundle\Utils\DtoDeserializerFactory', 'create' ]

    ITech\Bundle\DbalBundle\Utils\DtoDeserializerInterface:
         alias: ITech\Bundle\DbalBundle\Utils\DtoDeserializer

    # Манагеры
    ITech\Bundle\DbalBundle\DBAL\DbalManagerFactory:
        arguments:
            $dtoDeserializer: '@ITech\Bundle\DbalBundle\Utils\DtoDeserializerInterface'

    ITech\Bundle\DbalBundle\Manager\DbalManager:
        factory: [ '@ITech\Bundle\DbalBundle\DBAL\DbalManagerFactory', 'createByConnection' ]
        arguments:
            - '@Doctrine\DBAL\Connection'

    ITech\Bundle\DbalBundle\Service\TransactionService:
        arguments:
            - '@Doctrine\DBAL\Connection'
            - '%dbal.transaction_isolation_level%'

    ITech\Bundle\DbalBundle\Service\TransactionServiceInterface:
        alias: ITech\Bundle\DbalBundle\Service\TransactionService



