parameters:
    dbal.field_names:
        id: 'id'
        createdAt: 'created_at'
        updatedAt: 'updated_at'
        deletedAt: 'deleted_at'
    dbal.transaction_isolation_level: !php/const Doctrine\DBAL\TransactionIsolationLevel::REPEATABLE_READ
    dbal.use_auto_mapper: false
    dbal.default_dto_group: null
    dbal.chunk_size: 1000
    dbal.oder_direction: 'ASC'

services:

    # Deserializers
    Elrise\Bundle\DbalBundle\Service\Serialize\SymfonyDtoDeserializer:
        arguments:
            $serializer: '@serializer'
            $defaultGroup: '%dbal.default_dto_group%'

    Elrise\Bundle\DbalBundle\Service\Serialize\AutoMapperDtoDeserializer:
        arguments:
            $autoMapper: '@?AutoMapper\AutoMapperInterface'

    Elrise\Bundle\DbalBundle\Service\Serialize\DtoDeserializerFactory:
        arguments:
            $symfonyDeserializer: '@Elrise\Bundle\DbalBundle\Service\Serialize\SymfonyDtoDeserializer'
            $autoMapperDeserializer: '@?Elrise\Bundle\DbalBundle\Service\Serialize\AutoMapperDtoDeserializer'
            $useAutoMapper: '%dbal.use_auto_mapper%'

    Elrise\Bundle\DbalBundle\Service\Serialize\DtoDeserializer:
        factory: [ '@Elrise\Bundle\DbalBundle\Service\Serialize\DtoDeserializerFactory', 'create' ]

    Elrise\Bundle\DbalBundle\Service\Serialize\DtoDeserializerInterface:
         alias: Elrise\Bundle\DbalBundle\Service\Serialize\DtoDeserializer

    # Манагеры
    Elrise\Bundle\DbalBundle\Config\DbalBundleConfig:
        arguments:
            $useAutoMapper: '%dbal.use_auto_mapper%'
            $defaultDtoGroup: '%dbal.default_dto_group%'
            $chunkSize: '%dbal.chunk_size%'
            $fieldNames: '%dbal.field_names%'
            $orderDirection: '%dbal.oder_direction%'

    Elrise\Bundle\DbalBundle\Manager\Contract\DbalFinderInterface:
        alias: Elrise\Bundle\DbalBundle\Manager\Finder\DbalFinder

    Elrise\Bundle\DbalBundle\Manager\Finder\DbalFinder:
        arguments:
            $connection: '@Doctrine\DBAL\Connection'
            $deserializer: '@Elrise\Bundle\DbalBundle\Service\Serialize\DtoDeserializerInterface'

    Elrise\Bundle\DbalBundle\Manager\Contract\DbalMutatorInterface:
        alias: Elrise\Bundle\DbalBundle\Manager\Mutator\DbalMutator

    Elrise\Bundle\DbalBundle\Manager\Mutator\DbalMutator:
        arguments:
            $connection: '@Doctrine\DBAL\Connection'

    Elrise\Bundle\DbalBundle\Manager\Contract\CursorIteratorInterface:
        alias: Elrise\Bundle\DbalBundle\Manager\Iterator\CursorIterator


    Elrise\Bundle\DbalBundle\Manager\Iterator\CursorIterator:
        arguments:
            $connection: '@Doctrine\DBAL\Connection'
            $deserializer: '@Elrise\Bundle\DbalBundle\Service\Serialize\DtoDeserializerInterface'
            $config: '@Elrise\Bundle\DbalBundle\Config\DbalBundleConfig'

    Elrise\Bundle\DbalBundle\Manager\Contract\OffsetIteratorInterface:
        alias: Elrise\Bundle\DbalBundle\Manager\Iterator\OffsetIterator

    Elrise\Bundle\DbalBundle\Manager\Iterator\OffsetIterator:
        arguments:
            $connection: '@Doctrine\DBAL\Connection'
            $deserializer: '@Elrise\Bundle\DbalBundle\Service\Serialize\DtoDeserializerInterface'
            $config: '@Elrise\Bundle\DbalBundle\Config\DbalBundleConfig'

    Elrise\Bundle\DbalBundle\Manager\Bulk\AbstractDbalWriteExecutor:
        abstract: true
        arguments:
            $connection: '@Doctrine\DBAL\Connection'
            $config: '@Elrise\Bundle\DbalBundle\Config\DbalBundleConfig'
            $sqlBuilder: '@Elrise\Bundle\DbalBundle\Sql\Builder\SqlBuilderInterface'

    Elrise\Bundle\DbalBundle\Manager\Bulk\BulkInserter:
        parent: Elrise\Bundle\DbalBundle\Manager\Bulk\AbstractDbalWriteExecutor

    Elrise\Bundle\DbalBundle\Manager\Bulk\BulkUpdater:
        parent: Elrise\Bundle\DbalBundle\Manager\Bulk\AbstractDbalWriteExecutor

    Elrise\Bundle\DbalBundle\Manager\Bulk\BulkUpserter:
        parent: Elrise\Bundle\DbalBundle\Manager\Bulk\AbstractDbalWriteExecutor

    Elrise\Bundle\DbalBundle\Manager\Bulk\BulkDeleter:
        parent: Elrise\Bundle\DbalBundle\Manager\Bulk\AbstractDbalWriteExecutor

    Elrise\Bundle\DbalBundle\Manager\Contract\BulkInserterInterface:
        alias: Elrise\Bundle\DbalBundle\Manager\Bulk\BulkInserter

    Elrise\Bundle\DbalBundle\Manager\Contract\BulkUpdaterInterface:
        alias: Elrise\Bundle\DbalBundle\Manager\Bulk\BulkUpdater

    Elrise\Bundle\DbalBundle\Manager\Contract\BulkUpserterInterface:
        alias: Elrise\Bundle\DbalBundle\Manager\Bulk\BulkUpserter

    Elrise\Bundle\DbalBundle\Manager\Contract\BulkDeleterInterface:
        alias: Elrise\Bundle\DbalBundle\Manager\Bulk\BulkDeleter

    Elrise\Bundle\DbalBundle\Manager\DbalManagerFactory:
        arguments:
            $defaultConnection: '@Doctrine\DBAL\Connection'
            $deserializer: '@Elrise\Bundle\DbalBundle\Service\Serialize\DtoDeserializerInterface'


    Elrise\Bundle\DbalBundle\Manager\DbalManager:
        factory: [ '@Elrise\Bundle\DbalBundle\Manager\DbalManagerFactory', 'createManager' ]


    # Transactions
    Elrise\Bundle\DbalBundle\Service\Transaction\TransactionService:
        arguments:
            - '@Doctrine\DBAL\Connection'
            - '%dbal.transaction_isolation_level%'

    Elrise\Bundle\DbalBundle\Service\Transaction\TransactionServiceInterface:
        alias: Elrise\Bundle\DbalBundle\Service\Transaction\TransactionService


    # SQL Builder
    Elrise\Bundle\DbalBundle\Sql\Builder\SqlBuilderFactory:
        arguments:
            $connection: '@Doctrine\DBAL\Connection'

    Elrise\Bundle\DbalBundle\Sql\Builder\SqlBuilderInterface:
        factory: [ '@Elrise\Bundle\DbalBundle\Sql\Builder\SqlBuilderFactory', 'create' ]



